# Generated by Django 6.1.1 on 2026-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(default='akshay', max_length=255, unique=True),
        ),
    ]
